###
POST http://localhost:8080/executeSql
Content-Type: application/json

{
    "name": "ispong_test",
    "sql": "INSERT INTO to_table SELECT username,age FROM from_table WHERE age >19"
}


###
POST http://localhost:8080/getDeployLog
Content-Type: application/json

{
  "executeId": "e04a36e2-f364-494e-9aba-ed783871440c"
}
