###
GET http://localhost:8080/executeSql

###
GET http://localhost:8080/getDeployLog

###
GET http://localhost:8080/getJobId

###
GET http://localhost:8080/getJobStatus

###
GET http://localhost:8080/getJobException

###
GET http://localhost:8080/stopJob
